# Generated by Django 5.2.13 on 2026-04-24 16:59

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('airbnb_listing_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('booking_property_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('airbnb_ical_url', models.URLField(blank=True, null=True)),
                ('booking_ical_url', models.URLField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('max_guests', models.PositiveIntegerField(default=2)),
                ('base_price_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClaudeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('daily_report', 'Daily Report'), ('overlap_check', 'Overlap Check'), ('send_whatsapp', 'Send WhatsApp'), ('flag_inquiry', 'Flag Inquiry'), ('sync_reservations', 'Sync Reservations'), ('generate_report', 'Generate Report'), ('link_guest', 'Link Guest'), ('search_availability', 'Search Availability')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('triggered_by', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual'), ('webhook', 'Webhook')], default='manual', max_length=10)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='pms_claudet_status_afa34c_idx'), models.Index(fields=['task_type', 'created_at'], name='pms_claudet_task_ty_46edcd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('id_document_url', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_returning', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='pms_guest_last_na_b27838_idx'), models.Index(fields=['email'], name='pms_guest_email_a7de9d_idx'), models.Index(fields=['phone'], name='pms_guest_phone_33ef7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField(default=0, editable=False)),
                ('guests_count', models.PositiveIntegerField(default=1)),
                ('platform', models.CharField(choices=[('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('direct', 'Direct'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('platform_reservation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('total_price_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('platform_commission_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_revenue_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pms.guest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='pms.property')),
            ],
            options={
                'ordering': ['check_in'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('airbnb', 'Airbnb'), ('booking', 'Booking.com')], max_length=20)),
                ('external_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('content', models.TextField()),
                ('needs_reply', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField()),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='pms.guest')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='pms.reservation')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('direct', 'Direct')], max_length=20)),
                ('check_in_requested', models.DateField(blank=True, null=True)),
                ('check_out_requested', models.DateField(blank=True, null=True)),
                ('guests_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('replied', 'Replied'), ('converted', 'Converted to Reservation'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('content', models.TextField()),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='pms.guest')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='pms.property')),
                ('converted_reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry', to='pms.reservation')),
            ],
            options={
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestStay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField()),
                ('amount_paid_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform', models.CharField(choices=[('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('direct', 'Direct'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_stays', to='pms.guest')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_stays', to='pms.property')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_stay', to='pms.reservation')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_revenue_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_expenses_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_profit_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('avg_nightly_rate_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_nights_booked', models.PositiveIntegerField(default=0)),
                ('total_nights_free', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_reports', to='pms.property')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['property', 'period_start', 'period_end'], name='pms_financi_propert_50b9cc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('platform_fees', 'Platform Fees'), ('insurance', 'Insurance'), ('mortgage', 'Mortgage'), ('supplies', 'Supplies'), ('tax', 'Tax'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(blank=True, choices=[('one_time', 'One-Time'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True)),
                ('date', models.DateField()),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='pms.property')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['property', 'date'], name='pms_expense_propert_77abd8_idx'), models.Index(fields=['category', 'date'], name='pms_expense_categor_47f628_idx'), models.Index(fields=['recurring', 'recurrence_frequency'], name='pms_expense_recurri_21a7fa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['property', 'check_in', 'check_out'], name='pms_reserva_propert_49ef7b_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status', 'check_in'], name='pms_reserva_status_0c1812_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['platform', 'platform_reservation_id'], name='pms_reserva_platfor_0823b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='reservation_check_out_after_check_in'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('platform_reservation_id__isnull', False)), fields=('platform', 'platform_reservation_id'), name='unique_platform_reservation'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('external_uid__isnull', False)), fields=('platform', 'external_uid'), name='unique_platform_external_uid'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['needs_reply', 'read', 'sent_at'], name='pms_message_needs_r_4a9da4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['platform', 'sent_at'], name='pms_message_platfor_f13c74_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_message_id__isnull', False)), fields=('platform', 'external_message_id'), name='unique_platform_message'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['status', 'created_at'], name='pms_inquiry_status_282dce_idx'),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['check_in_requested', 'check_out_requested'], name='pms_inquiry_check_i_104925_idx'),
        ),
        migrations.AddIndex(
            model_name='gueststay',
            index=models.Index(fields=['guest', 'check_in'], name='pms_guestst_guest_i_51ed8d_idx'),
        ),
        migrations.AddIndex(
            model_name='gueststay',
            index=models.Index(fields=['property', 'check_in'], name='pms_guestst_propert_118003_idx'),
        ),
    ]
