# Generated by Django 5.2.13 on 2026-04-24 18:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='apartment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nightly_price_eur',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_due',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['unit_code'], name='pms_propert_unit_co_765909_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['active', 'name'], name='pms_propert_active_414bef_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['paid', 'payment_due'], name='pms_reserva_paid_cb5066_idx'),
        ),
    ]
