# Generated by Django 5.2.13 on 2026-04-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_property_apartment_type_property_notes_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reservation',
            name='pms_reserva_status_0c1812_idx',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='synced_at',
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='gueststay',
            name='platform',
            field=models.CharField(choices=[('private', 'Private'), ('airbnb', 'Airbnb'), ('booking', 'Booking.com')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='platform',
            field=models.CharField(choices=[('private', 'Private'), ('airbnb', 'Airbnb'), ('booking', 'Booking.com')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['guest_name'], name='pms_reserva_guest_n_495e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['guest_phone'], name='pms_reserva_guest_p_38dd55_idx'),
        ),
    ]
