# Generated by Django 5.2.13 on 2026-04-24 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_remove_reservation_pms_reserva_status_0c1812_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_code', models.CharField(blank=True, max_length=100)),
                ('new_code', models.CharField(blank=True, max_length=100)),
                ('date_changed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='door_code', to='pms.property')),
            ],
            options={
                'ordering': ['property__name'],
                'indexes': [models.Index(fields=['date_changed'], name='pms_doorcod_date_ch_c37856_idx')],
            },
        ),
        migrations.CreateModel(
            name='LockboxCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment_number', models.CharField(blank=True, max_length=100)),
                ('old_code', models.CharField(blank=True, max_length=100)),
                ('new_code', models.CharField(blank=True, max_length=100)),
                ('date_changed', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lockbox_codes', to='pms.property')),
            ],
            options={
                'ordering': ['apartment_number', 'created_at'],
                'indexes': [models.Index(fields=['apartment_number'], name='pms_lockbox_apartme_12cbd5_idx'), models.Index(fields=['property', 'date_changed'], name='pms_lockbox_propert_666187_idx')],
            },
        ),
    ]
