# Generated by Django 5.2.13 on 2026-04-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0004_doorcode_lockboxcode'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lockboxcode',
            name='pms_lockbox_propert_666187_idx',
        ),
        migrations.RemoveField(
            model_name='lockboxcode',
            name='property',
        ),
        migrations.AddIndex(
            model_name='lockboxcode',
            index=models.Index(fields=['date_changed'], name='pms_lockbox_date_ch_85dae2_idx'),
        ),
    ]
