# Generated by Django 5.2.13 on 2026-04-24 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_remove_lockboxcode_pms_lockbox_propert_666187_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Expense categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialObligation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['paid', 'due_date', 'company_name'],
                'indexes': [models.Index(fields=['paid', 'due_date'], name='pms_financi_paid_a4e031_idx')],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('monthly_value_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_year', models.PositiveIntegerField()),
                ('start_month', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('end_month', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['start_year', 'start_month', 'end_year', 'end_month'], name='pms_loan_start_y_a5cb43_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinanceExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('one_time', 'One time'), ('repeated', 'Repeated')], default='one_time', max_length=20)),
                ('start_year', models.PositiveIntegerField()),
                ('start_month', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('end_month', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_expenses', to='pms.expensecategory')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['frequency', 'start_year', 'start_month'], name='pms_finance_frequen_5d2925_idx'), models.Index(fields=['category', 'start_year', 'start_month'], name='pms_finance_categor_b1d86d_idx')],
            },
        ),
    ]
