# Generated by Django 5.2.13 on 2026-04-25 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0006_expensecategory_financialobligation_loan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
