# Generated by Django 5.2.13 on 2026-05-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0008_property_calendar_export_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='platform',
            field=models.CharField(choices=[('airstay', 'AirStay'), ('fleet', 'Fleet')], db_index=True, default='airstay', max_length=20),
        ),
    ]
