# Generated by Django 6.0.4 on 2026-05-13 21:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_add_property_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_id', models.UUIDField(db_index=True)),
                ('file', models.FileField(upload_to='reservations/attachments/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='doorcode',
            name='changed_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='color',
            field=models.CharField(blank=True, default='#6b7280', max_length=20),
        ),
        migrations.AddField(
            model_name='lockboxcode',
            name='changed_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='lockboxcode',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='property',
            name='auto_sync_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='sync_interval_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='property',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reservation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='gueststay',
            name='platform',
            field=models.CharField(choices=[('private', 'Private'), ('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('maintenance', 'Maintenance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='platform',
            field=models.CharField(choices=[('private', 'Private'), ('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('maintenance', 'Maintenance')], max_length=20),
        ),
        migrations.CreateModel(
            name='ApartmentCleanStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_cleaned', models.BooleanField(default=False)),
                ('cleaned_at', models.DateTimeField(blank=True, null=True)),
                ('cleaned_by', models.CharField(blank=True, max_length=150)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clean_status', to='pms.property')),
            ],
            options={
                'ordering': ['property__name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('reporter_name', models.CharField(blank=True, max_length=150)),
                ('reported_at', models.DateField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_issues', to='pms.property')),
            ],
            options={
                'ordering': ['-reported_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.FileField(upload_to='maintenance/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pms.maintenanceissue')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyTax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('tvsh', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tatim_ne_fitim', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='pms_monthly_year_0a41d3_idx')],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ReservationAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reservation_id', models.UUIDField(db_index=True)),
                ('changed_by', models.CharField(blank=True, max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['reservation_id', 'changed_at'], name='pms_reserva_reserva_9223cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=20)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='pms.property')),
            ],
            options={
                'ordering': ['-synced_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceissue',
            index=models.Index(fields=['property', 'reported_at'], name='pms_mainten_propert_dbf789_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['property', 'synced_at'], name='pms_synclog_propert_7d5e63_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['channel', 'synced_at'], name='pms_synclog_channel_664258_idx'),
        ),
    ]
