# Generated by Django 6.0.4 on 2026-05-22 19:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_add_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(max_length=30)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('nights', models.PositiveIntegerField(default=0, editable=False)),
                ('guests_count', models.PositiveIntegerField(default=1)),
                ('total_price_eur', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('price_breakdown', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('rejection_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingSiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('building_address', models.TextField(blank=True)),
                ('building_name', models.CharField(blank=True, max_length=255)),
                ('same_day_booking_enabled', models.BooleanField(default=True)),
                ('same_day_booking_cutoff_hour', models.PositiveIntegerField(default=18)),
                ('advance_booking_limit_months', models.PositiveIntegerField(default=12)),
                ('non_refundable_discount_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
            ],
            options={
                'verbose_name': 'Booking Site Settings',
                'verbose_name_plural': 'Booking Site Settings',
            },
        ),
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('all', 'All Properties'), ('property', 'Specific Property'), ('bedroom_group', 'Bedroom Group')], default='all', max_length=20)),
                ('bedroom_group', models.PositiveIntegerField(blank=True, null=True)),
                ('policy_type', models.CharField(choices=[('free', 'Free Cancellation'), ('partial', 'Partial Refund'), ('non_refundable', 'Non-Refundable')], max_length=20)),
                ('days_before_checkin', models.PositiveIntegerField(blank=True, help_text='Guest must cancel this many days before check-in for free cancellation', null=True)),
                ('refund_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Refund percentage for partial policy', max_digits=5, null=True)),
                ('auto_process', models.BooleanField(default=True, help_text='Automatically process cancellation/refund')),
            ],
            options={
                'ordering': ['scope', 'policy_type'],
            },
        ),
        migrations.CreateModel(
            name='HouseRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_type', models.CharField(choices=[('long_stay', 'Long Stay Discount'), ('seasonal', 'Seasonal / Date-Range Pricing'), ('last_minute', 'Last-Minute Discount'), ('minimum_nights', 'Minimum Nights')], max_length=20)),
                ('scope', models.CharField(choices=[('all', 'All Properties'), ('property', 'Specific Property'), ('bedroom_group', 'Bedroom Group')], default='all', max_length=20)),
                ('bedroom_group', models.PositiveIntegerField(blank=True, help_text='Number of bedrooms this rule targets', null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('min_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('days_before_checkin', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('adjustment_type', models.CharField(blank=True, choices=[('fixed_price', 'Fixed Nightly Price'), ('pct_increase', 'Percentage Increase'), ('pct_decrease', 'Percentage Decrease'), ('fixed_increase', 'Fixed Amount Increase'), ('fixed_decrease', 'Fixed Amount Decrease')], max_length=20, null=True)),
                ('adjustment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['rule_type', 'scope'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scope', models.CharField(choices=[('all', 'All Properties'), ('property', 'Specific Property'), ('bedroom_group', 'Bedroom Group')], default='all', max_length=20)),
                ('bedroom_group', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Null means unlimited', null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.FileField(upload_to='properties/photos/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='dailyentry',
            name='unique_platform_date',
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_active',
            field=models.BooleanField(default=True, help_text='Show on the public booking website'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_non_refundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='online_payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='online_payment_status',
            field=models.CharField(choices=[('none', 'No Online Payment'), ('first_night', 'First Night Paid'), ('full', 'Fully Paid Online')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price_breakdown_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gueststay',
            name='platform',
            field=models.CharField(choices=[('private', 'Private'), ('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('maintenance', 'Maintenance'), ('direct', 'Direct Booking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='receiptitemreservation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='platform',
            field=models.CharField(choices=[('private', 'Private'), ('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('maintenance', 'Maintenance'), ('direct', 'Direct Booking')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together={('platform', 'date')},
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_requests', to='pms.property'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_request', to='pms.reservation'),
        ),
        migrations.AddField(
            model_name='cancellationpolicy',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_policies', to='pms.property'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='pms.property'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='pms.property'),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pms.promocode'),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='amenity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='pms.amenity'),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='pms.property'),
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pms.property'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['status', 'expires_at'], name='pms_booking_status_3724f3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['property', 'check_in', 'check_out'], name='pms_booking_propert_1da8c6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(fields=['token'], name='pms_booking_token_ff5251_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyamenity',
            unique_together={('property', 'amenity')},
        ),
    ]
