# Generated by Django 5.2.13 on 2026-06-28 18:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_property_bathrooms_property_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='pinned_property',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(max_length=20)),
                ('external_uid', models.CharField(max_length=255)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('resolved', models.BooleanField(default=False)),
                ('existing_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_conflicts', to='pms.reservation')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_conflicts', to='pms.property')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['resolved', 'created_at'], name='pms_synccon_resolve_187caa_idx')],
                'constraints': [models.UniqueConstraint(fields=('property', 'channel', 'external_uid'), name='unique_sync_conflict')],
            },
        ),
    ]
