# Generated by Django 5.2.13 on 2026-07-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0015_reservation_pinned_property_syncconflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paid_months',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='gueststay',
            name='platform',
            field=models.CharField(choices=[('private', 'Private'), ('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('monthly', 'Monthly'), ('maintenance', 'Maintenance'), ('direct', 'Direct Booking')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='platform',
            field=models.CharField(choices=[('private', 'Private'), ('airbnb', 'Airbnb'), ('booking', 'Booking.com'), ('monthly', 'Monthly'), ('maintenance', 'Maintenance'), ('direct', 'Direct Booking')], max_length=20),
        ),
    ]
