# Generated by Django 5.2.13 on 2026-07-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0016_reservation_paid_months_alter_gueststay_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='hidden_from_management',
            field=models.BooleanField(default=False),
        ),
    ]
