# Generated by Django 5.2.13 on 2026-07-23 18:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0018_reservation_monthly_price_eur'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Kosovo', max_length=100)),
                ('tax_id', models.CharField(blank=True, help_text='Business number (NUI/NIF)', max_length=50)),
                ('vat_id', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='company/')),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('iban', models.CharField(blank=True, max_length=50)),
                ('swift', models.CharField(blank=True, max_length=20)),
                ('bank_name2', models.CharField(blank=True, max_length=255)),
                ('iban2', models.CharField(blank=True, max_length=50)),
                ('swift2', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Default VAT % on invoices', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company profile',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
