# Generated by Django 5.2.13 on 2026-07-23 18:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0019_companyprofile_property_latitude_property_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('paid', models.BooleanField(default=False)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('client_address', models.TextField(blank=True)),
                ('client_city', models.CharField(blank=True, max_length=100)),
                ('client_country', models.CharField(blank=True, max_length=100)),
                ('client_tax_id', models.CharField(blank=True, max_length=50)),
                ('client_vat_id', models.CharField(blank=True, max_length=50)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('line_items', models.JSONField(default=list)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('company_snapshot', models.JSONField(default=dict)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pms.guest')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pms.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='pms_invoice_status_22596a_idx'), models.Index(fields=['issue_date'], name='pms_invoice_issue_d_8e1edb_idx')],
            },
        ),
    ]
