# Generated by Django 5.2.13 on 2026-07-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0020_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeexpense',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='expenses/'),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financeexpense',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
