# Generated by Django 5.2.13 on 2026-07-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0021_financeexpense_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='prices_include_vat',
            field=models.BooleanField(default=True),
        ),
    ]
