# Generated by Django 5.2.13 on 2026-08-08 16:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0022_invoice_prices_include_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsitesettings',
            name='map_privacy_radius_m',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.CreateModel(
            name='GuestDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('passport', 'Passport'), ('national_id', 'National ID'), ('drivers_license', "Driver's license"), ('other', 'Other document')], default='other', max_length=20)),
                ('file', models.FileField(upload_to='guests/documents/')),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pms.guest')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('amount_eur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pms.financeexpense')),
            ],
            options={
                'ordering': ['year', 'month'],
                'indexes': [models.Index(fields=['year', 'month'], name='pms_expense_year_1bcc8b_idx')],
                'constraints': [models.UniqueConstraint(fields=('expense', 'year', 'month'), name='unique_expense_payment_month')],
            },
        ),
    ]
