# Generated by Django 5.2.13 on 2026-08-09 14:55

import pms.model_defs.guests
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0025_usersecurity_loginchallenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestdocument',
            name='file',
            field=models.FileField(upload_to=pms.model_defs.guests.guest_document_path),
        ),
    ]
