# Generated by Django 5.2.13 on 2026-08-20 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0026_alter_guestdocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('behaviour', models.CharField(choices=[('stack', 'Stack — every eligible rule applies, in order'), ('exclusive', 'Exclusive — the first eligible rule applies')], default='stack', max_length=10)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StayConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('min_nights', 'Minimum nights')], default='min_nights', max_length=20)),
                ('value', models.PositiveIntegerField()),
                ('scope', models.CharField(choices=[('all', 'All Properties'), ('property', 'Specific Property'), ('bedroom_group', 'Bedroom Group')], default='all', max_length=20)),
                ('bedroom_group', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'scope'],
            },
        ),
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'ordering': ['sort_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='promo_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_requests', to='pms.pricingrule'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='application',
            field=models.CharField(choices=[('per_night', 'Per night'), ('whole_stay', 'Whole stay')], default='whole_stay', max_length=12),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='min_subtotal_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Null means unlimited', null=True),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('long_stay', 'Long Stay Discount'), ('seasonal', 'Seasonal / Date-Range Pricing'), ('last_minute', 'Last-Minute Discount'), ('minimum_nights', 'Minimum Nights'), ('non_refundable', 'Non-Refundable Discount'), ('promo', 'Promo Code'), ('manual', 'Manual Discount')], max_length=20),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='pms.pricinggroup'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.UniqueConstraint(condition=models.Q(('code__isnull', False)), fields=('code',), name='pricingrule_code_unique_when_set'),
        ),
        migrations.AddField(
            model_name='stayconstraint',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stay_constraints', to='pms.property'),
        ),
    ]
