"""Split pricing between AirStay and Fleet.

Every pricing group and every stay constraint belonged to no platform, so one
set of rules priced both the apartments and the vehicles. A bedroom-based base
rate, a 28-night long-stay tier and a two-night minimum written for flats were
all being applied to car hires as well.

Existing configuration becomes AirStay's, since that is what it was written
for. Fleet gets the same five groups, empty: copying the rules across would
just reproduce the conflict as duplicates, and a rate keyed on bedroom count
means nothing for a vehicle. Fleet properties therefore have no base price
until one is set, which calculate_price reports as an error rather than
quoting a stay at zero.
"""

# Generated by Django 5.2.13 on 2026-08-20 19:57

from django.db import migrations, models


GROUPS = [
    ("Base Prices", "specific"),
    ("Seasonal Pricing", "stack"),
    ("Length of Stay Discounts", "best"),
    ("Booking Discounts", "stack"),
    ("Promotions", "stack"),
]


def give_fleet_its_own_groups(apps, schema_editor):
    PricingGroup = apps.get_model("pms", "PricingGroup")

    # Everything that exists was written for apartments.
    PricingGroup.objects.filter(platform="").update(platform="airstay")

    for sort_order, (name, behaviour) in enumerate(GROUPS):
        PricingGroup.objects.get_or_create(
            platform="fleet",
            name=name,
            defaults={"sort_order": sort_order, "behaviour": behaviour},
        )


def noop(apps, schema_editor):
    """No-op. Reversing would merge two rule sets back into one, which is the
    conflict this migration exists to end."""


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0034_drop_property_base_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricinggroup',
            name='platform',
            field=models.CharField(choices=[('airstay', 'AirStay'), ('fleet', 'Fleet')], db_index=True, default='airstay', max_length=20),
        ),
        migrations.AddField(
            model_name='stayconstraint',
            name='platform',
            field=models.CharField(choices=[('airstay', 'AirStay'), ('fleet', 'Fleet')], db_index=True, default='airstay', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricinggroup',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AddConstraint(
            model_name='pricinggroup',
            constraint=models.UniqueConstraint(fields=('platform', 'name'), name='unique_group_name_per_platform'),
        ),
        # After the schema, so `platform` exists to write to.
        migrations.RunPython(give_fleet_its_own_groups, noop),
    ]
