# Generated by Django 5.2.13 on 2026-08-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0035_platform_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('base_price', 'Base Price'), ('block_discounts', 'Exclude Discounts'), ('long_stay', 'Long Stay Discount'), ('seasonal', 'Seasonal / Date-Range Pricing'), ('last_minute', 'Last-Minute Discount'), ('non_refundable', 'Non-Refundable Discount'), ('promo', 'Promo Code'), ('manual', 'Manual Discount')], max_length=20),
        ),
    ]
