# Generated by Django 5.2.13 on 2026-08-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0036_block_discounts_rule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='blocks_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='pms.pricinggroup'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='blocks_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='pms.pricingrule'),
        ),
    ]
