# Generated by Django 5.2.13 on 2026-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0037_selective_discount_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingrule',
            name='stacks',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('base_price', 'Base Price'), ('block_discounts', 'Exclude Discounts'), ('date_adjust', 'Date Increase / Decrease'), ('long_stay', 'Long Stay Discount'), ('seasonal', 'Seasonal / Date-Range Pricing'), ('last_minute', 'Last-Minute Discount'), ('non_refundable', 'Non-Refundable Discount'), ('promo', 'Promo Code'), ('manual', 'Manual Discount')], max_length=20),
        ),
    ]
