# Generated by Django 5.2.13 on 2026-08-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0038_date_adjust_stacking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stayconstraint',
            name='kind',
            field=models.CharField(choices=[('min_nights', 'Minimum nights'), ('max_advance', 'Latest bookable date')], default='min_nights', max_length=20),
        ),
        migrations.AlterField(
            model_name='stayconstraint',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
