# Generated by Django 5.2.13 on 2026-08-20 23:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0039_booking_horizon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.CharField(choices=[('available', 'Apartments available'), ('split_stay', 'Split stay possible'), ('alternative_dates', 'Free on nearby dates'), ('no_availability', 'Fully booked')], max_length=32, unique=True)),
                ('body_sq', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['scenario'],
            },
        ),
    ]
