# Generated by Django 5.2.13 on 2026-08-22 14:12

"""Reservation types become an editable table instead of a frozen enum.

Also drops `choices` from the two platform columns. That is what let a
hand-added type be saved at all: Reservation.save() calls full_clean(), so a
code outside the enum was rejected outright. The guard it provided has not
been dropped, only moved — Reservation.clean() now rejects any code with no
row in this table.
"""

import uuid

from django.db import migrations, models

from ._0043_types import seed_types


def seed(apps, schema_editor):
    seed_types(apps)


def unseed(apps, schema_editor):
    """Reversing drops the table wholesale, so there is nothing to undo."""


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0042_discount_as_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('color', models.CharField(default='#6b7280', max_length=7)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_builtin', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.AlterField(
            model_name='gueststay',
            name='platform',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='platform',
            field=models.CharField(max_length=20),
        ),
        migrations.RunPython(seed, unseed),
    ]
