# Generated by Django 5.2.13 on 2026-08-22 14:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0043_reservation_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=3),
        ),
    ]
