# Generated by Django 5.2.13 on 2026-08-22 14:51

"""Two more templates: what the guest is told when a request is decided.

Before this the outcome never left the building — the rejection message
staff typed was saved and read by nobody, and an approval was silent.
"""

from django.db import migrations, models

from ._0045_lifecycle import seed_lifecycle_templates


def seed(apps, schema_editor):
    seed_lifecycle_templates(apps)


def unseed(apps, schema_editor):
    """Reversing would delete wording an operator may have edited."""


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0044_half_bathrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='scenario',
            field=models.CharField(choices=[('available', 'Apartments available'), ('split_stay', 'Split stay possible'), ('alternative_dates', 'Free on nearby dates'), ('no_availability', 'Fully booked'), ('booking_approved', 'Booking approved'), ('booking_rejected', 'Booking declined')], max_length=32, unique=True),
        ),
        migrations.RunPython(seed, unseed),
    ]
