# Generated by Django 5.2.13 on 2026-08-22 16:04

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0046_guest_accounts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookingrequest',
            index=models.Index(django.db.models.functions.text.Lower('guest_email'), name='bookingreq_email_lower'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(django.db.models.functions.text.Lower('guest_email'), name='reservation_email_lower'),
        ),
    ]
