# Generated by Django 5.2.13 on 2026-08-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0047_guest_email_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
