# Generated by Django 5.2.13 on 2026-08-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0048_guest_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='garage_card',
            field=models.BooleanField(default=False),
        ),
    ]
