# Generated by Django 5.2.13 on 2026-08-31 12:11

import uuid
from django.db import migrations, models

from ._0050_contracts import CONTRACTS


def seed_contracts(apps, schema_editor):
    ContractTemplate = apps.get_model("pms", "ContractTemplate")
    for kind, body_sq, body_en in CONTRACTS:
        ContractTemplate.objects.get_or_create(
            kind=kind, defaults={"body_sq": body_sq, "body_en": body_en}
        )


def drop_contracts(apps, schema_editor):
    ContractTemplate = apps.get_model("pms", "ContractTemplate")
    ContractTemplate.objects.filter(kind__in=[k for k, _, _ in CONTRACTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0049_reservation_garage_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('apartment', 'Apartment rental'), ('vehicle', 'Car rental')], max_length=20, unique=True)),
                ('body_sq', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.RunPython(seed_contracts, drop_contracts),
    ]
