# Generated by Django 5.2.13 on 2026-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0050_contract_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_registration_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_type',
            field=models.CharField(choices=[('business', 'Business'), ('individual', 'Individual')], default='business', max_length=12),
        ),
    ]
