# Generated by Django 5.2.13 on 2026-08-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0051_invoice_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='current_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='last_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='last_service_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='registration_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='service_interval_km',
            field=models.PositiveIntegerField(blank=True, default=10000, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='service_interval_months',
            field=models.PositiveIntegerField(blank=True, default=12, null=True),
        ),
    ]
