# Generated by Django 5.2.13 on 2026-09-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0054_contract_terms_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='allowed_countries',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='brand',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='property',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='property',
            name='licence_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='model',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
