# Generated by Django 5.2.13 on 2026-09-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0055_vehicle_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='registration_warning_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='property',
            name='service_warning_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='property',
            name='service_warning_km',
            field=models.PositiveIntegerField(default=800),
        ),
    ]
