# Generated by Django 5.2.13 on 2026-09-12 20:46

from django.db import migrations, models


def mark_sync_created(apps, schema_editor):
    """Backfill `created_by_sync` for rows the import made.

    Without this, every booking imported before the field existed would be
    exempt from reconciliation and a real channel cancellation would never
    clear off the calendar.

    The signal is the guest name: the import writes the channel's label
    ("Airbnb", "Booking.com") because the feed carries no guest name, whereas a
    booking someone typed in has a real one. Rows that were adopted - typed by
    hand and later matched to a feed event - keep `False`, which is the safe
    way round: the feed can update their dates but never cancel them.
    """
    Reservation = apps.get_model("pms", "Reservation")
    ReservationType = apps.get_model("pms", "ReservationType")

    labels = set()
    for code, label in ReservationType.objects.values_list("code", "label"):
        labels.update({(code or "").strip(), (label or "").strip()})
    labels.update({"Airbnb", "Booking.com", "booking", "Reserved"})
    labels.discard("")

    Reservation.objects.exclude(external_uid__isnull=True).exclude(
        external_uid=""
    ).filter(guest_name__in=labels).update(created_by_sync=True)


def unmark_sync_created(apps, schema_editor):
    apps.get_model("pms", "Reservation").objects.update(created_by_sync=False)


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0056_vehicle_warning_windows'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_by_sync',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='missing_from_sync_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synclog',
            name='missing_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(mark_sync_created, unmark_sync_created),
    ]
