# Generated by Django 5.2.13 on 2026-09-12 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0058_sync_schedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='en', max_length=2)),
                ('body', models.TextField(blank=True)),
                ('client_id_number', models.CharField(blank=True, max_length=60)),
                ('licence_number', models.CharField(blank=True, max_length=60)),
                ('deposit', models.CharField(blank=True, max_length=40)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_drafts', to='pms.reservation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('reservation', 'language'), name='unique_reservation_contract_language')],
            },
        ),
    ]
