# Generated by Django 5.2.13 on 2026-09-12 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0061_fix_rejection_segment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceissue',
            name='is_resolved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='maintenanceissue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='maintenanceissue',
            index=models.Index(fields=['is_resolved', 'reported_at'], name='pms_mainten_is_reso_48391c_idx'),
        ),
    ]
